### PR TITLE
feat: add Notflix theme

### PR DESCRIPTION
**Pull request by luwes**
https://player-style-git-netflix-mux.vercel.app/themes/notflix

- [x] responsiveness
- [x] icons
- [x] time display
- [x] add volume range
- [x] add subtitles menu

### CODE REVIEW

**Comment by heff** [comment]
I can work on it after YT. Is it good enough to pull in for now or more on the broken side of things?

**Comment by luwes** [comment]
yep, we can only add the package. not yet the site entry...

**Comment by heff** [comment]
I renamed it, rebased, and added to every list I could find because I wasn't sure how to get it to show up.

**Comment by luwes** [comment]
hmm can we leave it off the site list for now? 

the quality is lacking IMO.

- the seek button icons are not right
- the control bar is too high for small players
- the mobile view breaks
- no time display 
- no cc button

SCR-20240703-qupg

see https://netflixtechblog.com/modernizing-the-web-playback-ui-1ad2f184a5a0

**Comment by luwes** [comment]
reminder to change the theme date before merging so it's not the first in the home page list!!!!!!

**Review by heff — APPROVED** [review]

**Pull request merged**
